### ISSUE TITLE
How turn it undetectable for Windows Defender?

### ISSUE THREAD

**Issue by WorldWonderful10** [hackerhouse-opensource/ColorDataProxyUACBypass#2]
Nice xpl! but how turn it undetectable for Windows Defender? now is being detected on execution.

**Comment by hackerhouse-opensource** [comment]
These binaries are designed for assessment purposes only, evading Defender is outside of our scope of these implementations and left as an exercise for you.

**Comment by ybdt** [comment]
我这边测试，在Win10最新版21H2 19044.1889，VS2022编译后，Defender并不拦截，但是360会拦截
